site_name: Workshop CFDSUSTAIN - OpenLB
site_description: Workshop CFDSUSTAIN - OpenLB
site_author: Andreas Celada
site_url: https://ascelada.github.io/cfdsustain-workshop/

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - navigation.instant

nav:
  - Home: index.md
  - Setup:
    - Dependencias: setup/prerequisitos.md
    - Script de Setup: setup/setup.md
  - Cavidade 2D:
    - Problema: cavidade2d/01-problema.md
    - Executar: cavidade2d/02-compilar-executar.md
    - Parametros: cavidade2d/03-parametros.md
    # - Código: cavidade2d/04-codigo.md
    - Diagnosticos: cavidade2d/05-diagnosticos.md
  - Cilindro 2D:
    - Introdução: cilindro2d/index.md
    - Geometria: cilindro2d/geometria.md
    # - Visão Geral: cilindro2d/visao-geral.md
    - Tarefas:
      - Queda de Pressão: cilindro2d/tarefa1.md
      - Startup e Contorno: cilindro2d/tarefa1b.md
    - Código:
      - Código Original: cilindro2d/original.md
  - Bifurcação:
    - Introdução: particulas/index.md
    - Tarefa: particulas/tarefa.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed 
  - attr_list
  - md_in_html     # se você usa === "Tabs"

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

